---
benchmark:
  php:
    enabled: true
  disk:
    enabled: false
  cpu:
    enabled: true
    math:
      count: 99999
    strings:
      count: 99999
    loops:
      count: 99999
    ifElse:
      count: 99999
  mysql:
    enabled: false
